import { Plus_Jakarta_Sans } from "next/font/google";
import "./globals.css";
import AdminSidebar from "@/components/admin-sidebar";

const plusJakartaSans = Plus_Jakarta_Sans({
    variable: "--font-plus-jakarta-sans",
    subsets: ["latin"],
});

export const metadata = {
    title: "Internship Management System",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html
            lang="en"
            className={`${plusJakartaSans.variable}  h-full antialiased`}
        >
            <body className="h-screen overflow-hidden flex">
                <AdminSidebar />
                {children}
            </body>
        </html>
    );
}
